language: python
python:
  - "2.6"
before_install:
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv 7F0CEB10
  - sudo sh -c "echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' >> /etc/apt/sources.list"
  - sudo apt-get install mongodb-10gen
  - sudo apt-get install default-jre
install:
  - pip install -r requirements.pip --use-mirrors
  - python manage.py syncdb --noinput
  - python manage.py migrate --noinput
script: python manage.py test --noinput
notifications:
  irc: "irc.freenode.org#modilabs"
